export const mockStats = {
  totalEvents: 12,
  pendingTasks: 24,
  pendingPayments: 8,
  activeLeads: 15,
  revenue: 125000,
  completionRate: 78,
};

export const mockEvents = [
  {
    id: "1",
    name: "Boda García-López",
    couple: "María García & Carlos López",
    date: "2025-03-15",
    venue: "Hacienda Los Olivos",
    status: "in_progress",
    budget: 25000,
    spent: 18500,
    completion: 65,
    guests: 150,
  },
  {
    id: "2",
    name: "Boda Martínez-Ruiz",
    couple: "Ana Martínez & Pedro Ruiz",
    date: "2025-04-22",
    venue: "Hotel Grand Palace",
    status: "planning",
    budget: 35000,
    spent: 8000,
    completion: 25,
    guests: 200,
  },
  {
    id: "3",
    name: "Boda Fernández-Torres",
    couple: "Laura Fernández & Diego Torres",
    date: "2025-02-14",
    venue: "Jardín Botánico",
    status: "in_progress",
    budget: 18000,
    spent: 15200,
    completion: 85,
    guests: 80,
  },
  {
    id: "4",
    name: "Boda Sánchez-Moreno",
    couple: "Elena Sánchez & Juan Moreno",
    date: "2025-05-10",
    venue: "Castillo Medieval",
    status: "planning",
    budget: 45000,
    spent: 5000,
    completion: 15,
    guests: 250,
  },
  {
    id: "5",
    name: "Boda Rodríguez-Díaz",
    couple: "Carmen Rodríguez & Luis Díaz",
    date: "2025-01-28",
    venue: "Playa del Carmen",
    status: "completed",
    budget: 30000,
    spent: 28500,
    completion: 100,
    guests: 120,
  },
];

export const mockTasks = [
  {
    id: "1",
    title: "Confirmar menú con catering",
    eventId: "1",
    eventName: "Boda García-López",
    dueDate: "2025-01-20",
    status: "pending",
    priority: "high",
  },
  {
    id: "2",
    title: "Revisar contrato fotógrafo",
    eventId: "1",
    eventName: "Boda García-López",
    dueDate: "2025-01-18",
    status: "pending",
    priority: "medium",
  },
  {
    id: "3",
    title: "Enviar invitaciones",
    eventId: "2",
    eventName: "Boda Martínez-Ruiz",
    dueDate: "2025-02-01",
    status: "pending",
    priority: "high",
  },
  {
    id: "4",
    title: "Prueba de sonido",
    eventId: "3",
    eventName: "Boda Fernández-Torres",
    dueDate: "2025-02-10",
    status: "in_progress",
    priority: "medium",
  },
  {
    id: "5",
    title: "Confirmar transporte novios",
    eventId: "1",
    eventName: "Boda García-López",
    dueDate: "2025-03-10",
    status: "pending",
    priority: "low",
  },
];

export const mockVendors = [
  {
    id: "1",
    name: "Catering Deluxe",
    category: "Catering",
    rating: 4.8,
    contact: "info@cateringdeluxe.com",
    phone: "+34 612 345 678",
  },
  {
    id: "2",
    name: "Foto & Video Pro",
    category: "Fotografía",
    rating: 4.9,
    contact: "contacto@fotovideopro.com",
    phone: "+34 623 456 789",
  },
  {
    id: "3",
    name: "Flores del Valle",
    category: "Floristería",
    rating: 4.7,
    contact: "pedidos@floresdelvalle.com",
    phone: "+34 634 567 890",
  },
  {
    id: "4",
    name: "DJ Sounds",
    category: "Música",
    rating: 4.6,
    contact: "booking@djsounds.com",
    phone: "+34 645 678 901",
  },
];

export type Event = (typeof mockEvents)[0];
export type Task = (typeof mockTasks)[0];
export type Vendor = (typeof mockVendors)[0];
