// Auto-creates ClickUp tickets and sends notifications when errors are detected
// Deduplication: won't create duplicate tickets for same path+error within 24h

import { logger, type LogLevel, type LogContext } from "./logger";

interface ClickUpTicket {
  name: string;
  description: string;
  status: string;
  priority: number; // 1=urgent, 2=high, 3=normal, 4=low
  tags: string[];
}

// Track recently reported errors to avoid duplicates (path:errorMsg -> timestamp)
const recentReports = new Map<string, number>();
const DEDUP_WINDOW_MS = 24 * 60 * 60 * 1000; // 24 hours

function getClickUpConfig() {
  return {
    token: process.env.CLICKUP_API_TOKEN || "",
    listId: process.env.CLICKUP_MONITORING_LIST_ID || "901322179370",
  };
}

function severityToPriority(level: LogLevel): number {
  switch (level) {
    case "critical":
      return 1; // Urgent
    case "error":
      return 2; // High
    case "warn":
      return 3; // Normal
    default:
      return 4; // Low
  }
}

function buildDedupeKey(path: string, errorMessage: string): string {
  return `${path}::${errorMessage.slice(0, 100)}`;
}

function isDuplicate(key: string): boolean {
  const lastReported = recentReports.get(key);
  if (!lastReported) return false;
  if (Date.now() - lastReported > DEDUP_WINDOW_MS) {
    recentReports.delete(key);
    return false;
  }
  return true;
}

function cleanupOldReports() {
  const now = Date.now();
  for (const [key, timestamp] of recentReports.entries()) {
    if (now - timestamp > DEDUP_WINDOW_MS) {
      recentReports.delete(key);
    }
  }
}

async function createClickUpTicket(ticket: ClickUpTicket): Promise<string | null> {
  const config = getClickUpConfig();
  if (!config.token) {
    logger.warn("ClickUp token not configured, skipping ticket creation");
    return null;
  }

  try {
    const response = await fetch(
      `https://api.clickup.com/api/v2/list/${config.listId}/task`,
      {
        method: "POST",
        headers: {
          Authorization: config.token,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: ticket.name,
          description: ticket.description,
          status: ticket.status,
          priority: ticket.priority,
          tags: ticket.tags,
        }),
      }
    );

    if (!response.ok) {
      const text = await response.text();
      logger.error("Failed to create ClickUp ticket", {
        meta: { status: response.status, body: text },
      });
      return null;
    }

    const data = await response.json();
    logger.info(`ClickUp ticket created: ${data.id}`, {
      meta: { ticketId: data.id, ticketUrl: data.url },
    });
    return data.id;
  } catch (err) {
    logger.error("ClickUp API call failed", { error: err });
    return null;
  }
}

function buildTicketDescription(context: LogContext, errorMessage: string, stack?: string): string {
  const sections: string[] = [];

  sections.push(`## Error Details`);
  sections.push(`**Message:** ${errorMessage}`);
  sections.push(`**Timestamp:** ${new Date().toISOString()}`);

  if (context.method && context.path) {
    sections.push(`**Endpoint:** \`${context.method} ${context.path}\``);
  }
  if (context.statusCode) {
    sections.push(`**Status Code:** ${context.statusCode}`);
  }
  if (context.durationMs !== undefined) {
    sections.push(`**Response Time:** ${context.durationMs}ms`);
  }

  sections.push("");
  sections.push(`## Context`);
  if (context.userId) sections.push(`**User ID:** ${context.userId}`);
  if (context.orgId) sections.push(`**Org ID:** ${context.orgId}`);
  if (context.requestId) sections.push(`**Request ID:** ${context.requestId}`);

  if (stack) {
    sections.push("");
    sections.push(`## Stack Trace`);
    sections.push("```");
    sections.push(stack.slice(0, 2000));
    sections.push("```");
  }

  if (context.meta && Object.keys(context.meta).length > 0) {
    sections.push("");
    sections.push(`## Additional Meta`);
    sections.push("```json");
    sections.push(JSON.stringify(context.meta, null, 2).slice(0, 1000));
    sections.push("```");
  }

  sections.push("");
  sections.push(`---`);
  sections.push(`*Auto-generated by HubEnts Monitoring System*`);

  return sections.join("\n");
}

export async function reportError(
  level: LogLevel,
  message: string,
  context: LogContext = {}
): Promise<string | null> {
  // Log first
  const entry = logger[level](message, context);

  // Only create tickets for error and critical
  if (level !== "error" && level !== "critical") {
    return null;
  }

  // Deduplication
  const path = context.path || "unknown";
  const errorMsg = context.error instanceof Error ? context.error.message : message;
  const dedupeKey = buildDedupeKey(path, errorMsg);

  if (isDuplicate(dedupeKey)) {
    logger.info(`Skipping duplicate ticket for: ${dedupeKey}`);
    return null;
  }

  // Cleanup old entries periodically
  if (recentReports.size > 100) {
    cleanupOldReports();
  }

  // Mark as reported
  recentReports.set(dedupeKey, Date.now());

  // Build ticket
  const ticketName = `[AUTO] ${context.statusCode || "ERR"} en ${context.method || ""} ${path}`.trim();
  const description = buildTicketDescription(context, entry.message, entry.stack);

  const ticketId = await createClickUpTicket({
    name: ticketName.slice(0, 200),
    description,
    status: level === "critical" ? "in progress" : "to do",
    priority: severityToPriority(level),
    tags: ["bug", "auto-detected", level],
  });

  return ticketId;
}

export async function reportHealthCheckFailure(
  serviceName: string,
  error: string,
  details?: Record<string, unknown>
): Promise<string | null> {
  const dedupeKey = `health::${serviceName}::${error.slice(0, 50)}`;

  if (isDuplicate(dedupeKey)) {
    return null;
  }

  recentReports.set(dedupeKey, Date.now());

  const ticketId = await createClickUpTicket({
    name: `[HEALTH] ${serviceName} - ${error}`.slice(0, 200),
    description: buildTicketDescription(
      { meta: details },
      `Health check failed for ${serviceName}: ${error}`
    ),
    status: "to do",
    priority: 1, // Health failures are always urgent
    tags: ["infrastructure", "auto-detected", "health-check"],
  });

  return ticketId;
}

export function getReportStats() {
  return {
    recentReportsCount: recentReports.size,
    recentReports: Array.from(recentReports.entries()).map(([key, ts]) => ({
      key,
      reportedAt: new Date(ts).toISOString(),
    })),
  };
}
